spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/security_system}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
  jpa:
    hibernate.ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
access.system:
  usersMax: ${USERS_MAX:5}
  roomsMax: ${ROOMS_MAX:10000}